image: Ubuntu2004 # образ для сборки
stack: node 18 # окружение
branches:
 only:
    - master # ветка git
cache: node_modules # кеширование
install:
  - npm install # команда установки зависимостей
build: off
test_script:
  - npm run fix && npm lint && npm test # скрипт сборки
  # - npm run lint && npm test # скрипт сборки
